name: Build & Deploy delavega-app

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install and build
        run:  |
              npm ci
              npm test
              npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: master
          folder: build